
/*
 * Editor client script for DB table Songs
 * Automatically generated by http://editor.datatables.net/generator
 */

(function($){

$(document).ready(function() {
	var editor = new $.fn.dataTable.Editor( {
		"ajaxUrl": "php/table.Songs.php",
		"domTable": "#Songs",
		"fields": [
			{
				"label": "Name",
				"name": "Name",
				"type": "text"
			},
			{
				"label": "Time",
				"name": "Time",
				"type": "text"
			},
			{
				"label": "Artist",
				"name": "Artist",
				"type": "text"
			},
            {
                "label": "Album",
                "name": "Album",
                "type": "text"
            },
			{
				"label": "Genre",
				"name": "Genre",
				"type": "text"
			},
			{
				"label": "Plays",
				"name": "Plays",
				"type": "text"
			},
            {
				"label": "Video",
				"name": "Video",
				"type": "text"
			},
            
		]
	} );

	$('#Songs').dataTable( {
		"sDom": "Tfrtip",
		"sAjaxSource": "php/table.Songs.php",
        
		"aoColumns": [
			{
				"mDataProp": "Name"
			},
			{
				"mDataProp": "Time"
			},
			{
				"mDataProp": "Artist"
			},
            {
                "mDataProp": "Album"
            },
			{
				"mDataProp": "Genre"
			},
			{
				"mDataProp": "Plays"
			},
            {
				"mDataProp": "Video",
                "bVisible": false
			},
            
		],
		"oTableTools": {
			"sRowSelect": "single",
            
            /* Name   null,
            /* Time   null,
            /* Artist null,
            /* Album  null,
            /* Genre  null,
            /* Plays  null,
            /* VideoID {  "bVisible": false,
                            "bSearchable": false},
            ]*/
			"aButtons": [
				{ "sExtends": "editor_create", "editor": editor },
				/*{ "sExtends": "editor_edit",   "editor": editor },*/
				{ "sExtends": "editor_remove", "editor": editor }
			]
            
		}
	} );
} );

}(jQuery));

