
-- 
-- Editor server script for DB table Songs
-- Automatically generated by http://editor.datatables.net/generator
-- 

CREATE TABLE `Songs` (
	`id` int(10) NOT NULL auto_increment,
	`Name` varchar(255) default NULL,
	`Time` varchar(255) default NULL,
	`Artist` varchar(255) default NULL,
	'Album' varchar(255) default NULL,
	`Genre` varchar(255) default NULL,
	`Plays` varchar(255) default NULL,
	'Video' varchar(255) default NULL,
	PRIMARY KEY  (`id`)
);

